### ISSUE TITLE
Parse error: syntax error, unexpected '$_ENV' (T_VARIABLE) in /var/www/classes/PDO.class.php on line 6

### ISSUE THREAD

**Issue by KoenCodesStuff** [HECommunity/HackerExperience#3]
I get this error: Parse error: syntax error, unexpected '$_ENV' (T_VARIABLE) in /var/www/classes/PDO.class.php on line 6
Can somebody help me?
Info:
PHP Version 5.6

**Comment by KoenCodesStuff** [comment]
Nevermind i figured it out.

**Comment by Maxix25** [comment]
Hey, what was the error?
